/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef friend_service_CONSTANTS_H
#define friend_service_CONSTANTS_H

#include "friend_service_types.h"



class friend_serviceConstants {
 public:
  friend_serviceConstants();

};

extern const friend_serviceConstants g_friend_service_constants;



#endif
