/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "friend_service_constants.h"



const friend_serviceConstants g_friend_service_constants;

friend_serviceConstants::friend_serviceConstants() {
}



